#!/usr/bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6 

bspc config border_width         4
bspc config window_gap          15

bspc config top_padding          60
bspc config left_padding         5
bspc config right_padding        5
bspc config bottom_padding       5

bspc config split_ratio                   0.51
bspc config single_monocle                true
bspc config borderless_monocle            false
bspc config gapless_monocle               false

bspc config focus_follows_pointer         false
bspc config pointer_follows_focus         false
bspc config pointer_motion_interval       5
bspc config pointer_modifier              mod4 
bspc config pointer_action1               move 
bspc config pointer_action2               resize_side 
bspc config pointer_action3               resize_corner

bspc config normal_border_color  "#6e738d"
bspc config focused_border_color "#b7bdf8"

$HOME/.fehbg &

picom --config ~/.config/picom/picom.conf &
$HOME/.config/polybar/launch.sh &
